# WordPress Configuration
 
- name: Download and unpack latest WordPress
  unarchive:
    src: "{{ tar_file }}"
    dest: "{{ doc_root }}"
    remote_src: yes
    creates: "{{ doc_root }}/wordpress"

- name: Set ownership
  file:
    path: "{{ doc_root }}"
    state: directory
    recurse: yes
    owner: apache
    group: apache
 
- name: Set permissions for directories
  shell: "/usr/bin/find {{ doc_root }}/wordpress/ -type d -exec chmod 750 {} \\;"
- name: Set permissions for files
  shell: "/usr/bin/find {{ doc_root }}/wordpress/ -type f -exec chmod 640 {} \\;"

- name: Copy sample config file
  copy: 
    src: "{{ doc_root }}/wordpress/wp-config-sample.php" 
    dest: "{{ doc_root }}/wordpress/wp-config.php"
    remote_src: true
  become: yes
  ignore_errors: true
- name:  Remove old config sample file
  file: 
    path: "{{ doc_root }}/wordpress/wp-config-sample.php"
    state: absent
- name: Update WordPress config file
  lineinfile:
    path: "{{ doc_root }}/wordpress/wp-config.php"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{mysql_db}}' );"}
    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{mysql_user}}' );"}
    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{mysql_password}}' );"}
   
- name: Restart httpd service
  service: 
       name: "{{ service }}" 
       state: restarted
  become: yes
